### ISSUE TITLE
Error: elm.parentsUntil is not a function

### ISSUE THREAD

**Issue by majestixx** [softwaredoug/inspector-gadget#4]
Hey,
I am not able to get even a simple example running. I always get the following error (in FF):

```
Error: elm.parentsUntil is not a function
rootNode@http://localhost/xrel2frontend/inspector-gadget/inspector-gadget.js:28:32
link@http://localhost/xrel2frontend/inspector-gadget/inspector-gadget.js:66:20
.compile/<@http://localhost/xrel2frontend/inspector-gadget/inspector-gadget.js:161:13
nodeLinkFn@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.js:6579:13
compositeLinkFn@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.js:5982:15
compositeLinkFn@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.js:5989:13
publicLinkFn@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.js:5891:30
bootstrap/doBootstrap/</<@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.js:1384:11
$RootScopeProvider/this.$get</Scope.prototype.$eval@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.js:12412:16
$RootScopeProvider/this.$get</Scope.prototype.$apply@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.js:12510:18
bootstrap/doBootstrap/<@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.js:1382:9
invoke@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.js:3869:14
bootstrap/doBootstrap@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.js:1380:1
bootstrap@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.js:1394:1
angularInit@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.js:1307:5
@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.js:21459:5
trigger@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.js:2509:7
createEventHandler/eventHandler/<@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.js:2780:7
forEach@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.js:330:11
createEventHandler/eventHandler@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.js:2779:5
<inspector-gadget>
```

In Chromium the error is:

```
TypeError: undefined is not a function
    at rootNode (http://localhost/xrel2frontend/inspector-gadget/inspector-gadget.js:28:36)
    at link (http://localhost/xrel2frontend/inspector-gadget/inspector-gadget.js:66:20)
    at http://localhost/xrel2frontend/inspector-gadget/inspector-gadget.js:161:13
    at nodeLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.js:6579:13)
    at compositeLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.js:5982:15)
    at compositeLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.js:5989:13)
    at publicLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.js:5891:30)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.js:1384:27
    at Scope.$eval (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.js:12412:28)
    at Scope.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.js:12510:23) <inspector-gadget> 
```

My simple test file is:

``` html
<!DOCTYPE html>
<html>
<head>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.js"></script>
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
  <script src="inspector-gadget/inspector-gadget.js"></script>

  <script>
  var clientApp = angular.module('clientApp', ['swd.inspector-gadget']);
  </script>

  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" type="text/css" rel="stylesheet">
</head>
<body  data-ng-app="clientApp">
  <inspector-gadget>
      <a href="#">asdf</a>
      <inspector-title>
        asdfasdf
      </inspector-title>
      <inspector-content>
        <a href='asdfa'>Link to release</a>
      </inspector-content>
  </inspector-gadget>
</body>
</html>
```

Do you have any idea what is going wrong?

**Comment by softwaredoug** [comment]
Thanks for giving this a try. 

First thing I noticed was you need to have jquery before angular, the correct way to use jquery with angular is in the following include order:

```
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.js"></script>
```

Otherwise you're getting angular's jqLite.

Once you have that done, it will work, but the popover will go off the right of the browser window. You probably want to either style the class "popover-anchor" to set the width of the content on the page directly, or perhaps preferably wrap inspector-gadget in a div with specified dimensions. IE:

```
<div style="max-width: 50px">
  <inspector-gadget>
      <div style="max-width: 100px">
        <a href="#">asdf</a>
      </div>
      <inspector-title>
        asdfasdf
      </inspector-title>
      <inspector-content>
        <a href='asdfa'>Link to release</a>
      </inspector-content>
  </inspector-gadget>
</div>
```

Let me know if that helps you!

**Comment by majestixx** [comment]
Thank you very much.
Reordering the includes solved the issue!

Thanks for your work with this great tool.
